version: "3.8"

services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        - ENV_FILE=./docker/.env.local
    env_file: .env.local
    # volumes:
    #   - ../src:/app
    # command: sleep 5000
  mongodb:
    env_file: .env.local

  mongo_express:
    env_file: .env.local

  mqtt-broker:
    #    <<: *user
    image: eclipse-mosquitto:latest
    user: mosquitto
    volumes:
      - ./mqtt:/mosquitto/config/
      #    - ./log:/mosquitto/log/:rw
      - ./mqtt/data:/mosquitto/data
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - delta-core-net
